---
title: "CDCstuff"
author: "Eric Cavanna"
date: "`r Sys.Date()`"
output: word_document
---

```{r starts, include=F}
start.time <- Sys.time()
library(dplyr)
library(psych) #for KMO
library(GPArotation)
library(tidyverse)
library(ggplot2)

scale0_1 <- function(x){(x-min(x))/(max(x)-min(x))}
```


```{r getData}
#imports data
cdc = read.csv("C:/Users/Ecava/OneDrive/Desktop/research/SVI2020_US.csv", header = TRUE)

#names of cols to keep
colsKeep = c("STATE","ST_ABBR","COUNTY","FIPS", "E_TOTPOP", "EP_POV150", "EP_UNEMP", "EP_HBURD","EP_NOHSDP", "EP_UNINSUR", "EP_AGE65", "EP_AGE17",  "EP_DISABL", "EP_SNGPNT", "EP_LIMENG","EP_MINRTY", "EP_MUNIT", "EP_MOBILE","EP_CROWD",  "EP_NOVEH","EP_GROUPQ","RPL_THEMES")

#reduces size of cdc 
cdcFul <- cdc[,colsKeep]
```

```{r dataCleaning}
#remove tracts with out populaition
cdcFul <- cdcFul[cdcFul$RPL_THEMES != -999,]

#removes NAs
cdcFul <- na.omit(cdcFul)
```


```{r Completness}
#there is enough info so we can used just the complete ones
# aka removes duplicate zips
length(unique(cdcFul$FIPS))

#only keeps unique values for each tract
dim(cdcFul)

RPL_themes_his <- hist(cdcFul$RPL_THEMES, breaks = 100) #, xlab = "CDC SVI", main = NA)
```

```{r FactorAnalysisAssumpitons}
#Kaiser-meyer-olkin test
cdcRedu <- cdcFul[,5:21]
cdcCorMatrix <- cor(cdcRedu)
kmo <- KMO(r = cdcCorMatrix)
kmo$MSA #this is >> .6, can do FA

#calc and plots eigen vals
cdcFA <- fa(cdcRedu,nfactors = 5, rotate = "none")
plot(cdcFA$e.values, ylab = "Eigen vals")

#parallel <- fa.parallel(cdcRedu)
```


```{r FactorAnalysis}
cdcFA <- fa(cdcRedu, nfactors = 1,
            fm = "pa", max.iter = 100,
            rotation = "promax")

# % var explained by factor
ss <- colSums(cdcFA$Structure^2)
ss/length(cdcFA$communality)

#joins scores to bigger data base
scoresFA <- cdcFA$scores
tractFA <- cbind(cdcFul,scoresFA)[,c("FIPS","PA1")]
cdcFAtract <- left_join(cdcFul, tractFA, by="FIPS")

#adds name to last column
names(cdcFAtract)[length(names(cdcFAtract))] <- paste("FULL","PA1",sep = "_")

#pearson corelation test
cor.test(scoresFA,cdcFul$RPL_THEMES, method = "pearson")

scoresScalled <- scale0_1(scoresFA)
FA_hist <- hist(scoresScalled,breaks = 100)
```

```{r histss}
#pretty picture

plot(FA_hist, col=rgb(0,0,1,1/4), xlab = NA, main = NA)  # first histogram
plot(RPL_themes_his, col=rgb(1,0,0,1/4), add=T, main = NA)  # second
legend("topright",title = "Datasets",legend = c("SVI currently calculated by CDC", "SVI calculated by FA, scalled from 0-1 for comparison"), 
        fill = c(rgb(1,0,0,1/4), rgb(0,0,1,1/4)), cex = .6, 
       box.lty = 2)
```



```{r writeData}
write.csv(cdcFul, "C:\\Users\\Ecava\\OneDrive\\Desktop\\research\\cdcFul_FIPS.csv", row.names=FALSE)
write.csv(cdcFAtract, "C:\\Users\\Ecava\\OneDrive\\Desktop\\research\\cdcFAtract_FIPS.csv", row.names=FALSE)
```

```{r endTime}
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```
















